spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:63306/gridge-test-db?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root-pass

  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

kakao:
  client:
    id: ENC(Huq7OzVS7/Nttx9gSX+b9djqHoYFmqBVumZrQn63KTz5OvgUYawtp6yAvWL33igh)
    secret: ENC(ylKuoRG0eaRukuX/eGHlFPixud82hyV69edXHj2gu0G05SvIua+xkDU5LyDF0MPg)
    redirect-url: http://localhost:8080/auth/kakao/callback
    grant-type: authorization_code

token:
  secret: ENC(Pa9x0pV7pdfFTP2lpY6Y63TOeJP50xedpx5Y+P83OPc=)
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

sms:
  key: ENC(cnyiZ+ek7TsS9H2RXG/q3RxRbN+wYHdVDoNrLFiMzlI=)
  secret: ENC(Y0F4Gu8z3Iq5DxQMZ+TRL/ay2v4YxiwKt10MwJLKV9sL7oQt9UsMVLHXK7JzrHDR)
  to_phone_number: ENC(qnQHa4sUNlXpfitwq9ydwFZJko1O+x0a)
